# Generated by Django 3.0.2 on 2020-08-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('company', models.CharField(default=None, max_length=50, null=True, verbose_name='公司名称')),
                ('consulting', models.CharField(default=None, max_length=5000, null=True, verbose_name='咨询内容')),
            ],
        ),
    ]
