# Generated by Django 3.0.2 on 2020-08-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
